### ISSUE TITLE
Spacing of pause and play symbols

### ISSUE THREAD

**Issue by indicatelovelace** [Andeskjerf/waybar-module-pomodoro#1]
https://github.com/Andeskjerf/waybar-module-pomodoro/blob/97a4064f6bd2096f6d536e069424cdad358f44ad/src/main.rs#L114C47-L114C49
Would you mind adding a space after the pause symbol? It looks akward this way when the timer is ticking.

**Comment by Andeskjerf** [comment]
There's already a space for both play and pause :) It looks fine with a single space on my end. Though I'm sure it might look awkward with certain fonts.

![1715683864](https://github.com/Andeskjerf/waybar-module-pomodoro/assets/6963524/e004d47b-a4dd-4265-85c6-f965a405ff89)

**Comment by Andeskjerf** [comment]
https://github.com/Andeskjerf/waybar-module-pomodoro/pull/5 The icon/text can now be any custom value, so this issue is no longer relevant.
