### ISSUE TITLE
Disabling the hourglass icons, so only the timer can be visible.

### ISSUE THREAD

**Issue by kupkapandy** [Andeskjerf/waybar-module-pomodoro#10]
Problem described in title. If it's possible please tell me how. Thanks in advance.

**Comment by kupkapandy** [comment]
Found it

**Comment by Drexxl-the-Walrus** [comment]
How did you do this?

**Comment by Andeskjerf** [comment]
> How did you do this?

You can set the work & break icon to an empty string, using `-o '' -b ''`. I should probably add a flag to disable the icons, just to make it more consistent with the other flag :stuck_out_tongue:
