### ISSUE TITLE
Restore previous timer state after system reboot

### ISSUE THREAD

**Issue by khushal-banks** [Andeskjerf/waybar-module-pomodoro#16]
First of all thank you for this amazing module.
This is really great to have a pomodoro timer on my waybar.

I miss one little thing though, i want pomodoro timer to restore to previous state after a system reboot. (Say, i want to continue my work after reaching home)

Can we use ~/.cache/ or ~/.local/ to store the timer state every time it updates? and then use it to restore the old state (adjust new configuration or socket_nr) and continue the timer from where we left it before shutdown ?

**Comment by Andeskjerf** [comment]
Hmm.. We could do this, but I'm not sure how practical it is? If there's 15 minutes left of a work cycle and I leave work and resume when I get home, do I want to resume that session when I get back or just start over? Personally I'd consider that a new session and I'd start over.

**Comment by khushal-banks** [comment]
I agree. Starting a new session makes more sense to me considering practical application.

_Can we make this configurable? and let the user decide_
We always have the **reset button** on waybar if we want to start a new session, right?

I am more interested to know your thoughts. Would it be a better enhancement or worse? 
Considering this feature is configurable it would be harmless to normal use-case, right?
