### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by rlopzc** [Andeskjerf/waybar-module-pomodoro#2]
Hey! This is great, I'm currently using it, and it works flawlessly with Waybar.

My only issue is that there are no notifications, so I don't know when I completed the work/rest time.

What would it take to add notifications when finishing each timer (work/rest)?

**Comment by Andeskjerf** [comment]
Hey! Glad to hear it's working well for you! I've added notifications, https://github.com/Andeskjerf/waybar-module-pomodoro/commit/83c8a16085c2036c435a226849d8a5d1a1e19e2a :)
