### ISSUE TITLE
CSS classes?

### ISSUE THREAD

**Issue by BEST8OY** [Andeskjerf/waybar-module-pomodoro#4]
Hello
First, thanks for the module.
My question:
What are the CSS classes?
I expected things like these.
```css
#custom-pomodoro /* for when pomodoro is not started */
#custom-pomodoro.work
#custom-pomodoro.break
#custom-pomodoro.pause /* for when it's paused */
```
It would be nice to have them.
Update:
I just saw we actually have class for work and break
```rust
       let class = if state.current_index == 0 {
            "work"
        } else {
            "break"
        };
```
I wish to have pause and not started state the same CSS configuration which is not achievable as of now!

**Comment by BEST8OY** [comment]
Can we also be able to choose play and pause icon? because I have problem with default **pause button** of Nerd fonts (it somehow changes the position of the text; a tiny tiny bit to up)
We can use alternative pause button from here which solves the issue (for me at least)
https://www.nerdfonts.com/cheat-sheet

**Comment by Andeskjerf** [comment]
Thanks for the feedback! I've added the classes you were missing :)

Which pause icon are you referring to, that fixes it? nf-md-pause?

**Comment by BEST8OY** [comment]
> Thanks for the feedback! I've added the classes you were missing :)
> 
> Which pause icon are you referring to, that fixes it? nf-md-pause?

Yes
nf-md-pause and nf-md-play are fine
But I like these more nf-fa-pause and nf-fa-play

**Comment by Andeskjerf** [comment]
Let me know if you run into any problems! The icons for work & break are no longer set by the module configuration by the way, but instead via arguments to the module. I ran into issues where the icons and CSS rules would no longer apply if the class was set to "pause work" for example. The work & break icons were previously set if the class was "work" or "break".

**Comment by BEST8OY** [comment]
> Let me know if you run into any problems! The icons for work & break are no longer set by the module configuration by the way, but instead via arguments to the module. I ran into issues where the icons and CSS rules would no longer apply if the class was set to "pause work" for example. The work & break icons were previously set if the class was "work" or "break".

It's perfect now
With previous version work and break icon had wrong padding by default (they were too much to the right) for me so I had to add a padding of 10px to right to fix it but now that's fixed as well.
Thanks a bunch.
