### ISSUE TITLE
Bug with icon + feature request

### ISSUE THREAD

**Issue by BEST8OY** [Andeskjerf/waybar-module-pomodoro#6]
Hello again
There is a bug with work and break icon
Only the first work cycle has the work icon and from the first break then on it only shows break icon not the work icon.
This is an image of second work cycle ( I didn't use - o or -b flag)
![pic-selected-240723-2033-38](https://github.com/user-attachments/assets/ae514672-a85c-44fe-88a2-35740c68065f)

And about the feature reaquest

I wish if possible to have two flags in executing the pomodoro
1- Something like ```--autow``` which starts work sessions automatically
2- Something like ```--autob``` which starts break sessions automatically

**Comment by Andeskjerf** [comment]
Oops, that's what I get for not properly testing :stuck_out_tongue: The icon bug should be fixed here https://github.com/Andeskjerf/waybar-module-pomodoro/commit/21fb5bfe9249c45c1159183cdc556e503e2ce36d

The flags you mentioned have also been added :)
