### ISSUE TITLE
problem with pkill -RTMIN+N

### ISSUE THREAD

**Issue by BEST8OY** [Andeskjerf/waybar-module-pomodoro#8]
Hello again
I have a script that uses signals to update its status.
The problem is whenever I run a command like ```pkill -RTMIN+1 waybar``` the pomodoro hangs(unresponsive).
And to make it work again I have to delete the pomodoro socket files from /tmp and restart Waybar.
```zsh
[hl@DIAMOND ~]$ pkill -RTMIN+1 waybar       
[hl@DIAMOND ~]$ waybar-module-pomodoro reset
Error: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
```
Is it a Waybar issue or pomodoro module issue?

This is the script
```bash
#!/bin/sh

icon=$(cat /tmp/recordingicon 2>/dev/null)
if [ -z "$icon" ]; then
    echo ""
else
    echo "$icon"
fi
```

**Comment by Andeskjerf** [comment]
This was a weird one! Not sure why, but the module terminates if that signal is sent. I got it to work in the PR on my end, could you verify that it works on your end as well?

**Comment by BEST8OY** [comment]
Yes, this solved it for me too.
Thank you.
